devices:
    common:
    - /dev/i2c-0
    debug: []
    release: []
dockercomposefile:
    common: ''
    debug: ''
    release: ''
extraparms:
    common: {}
    debug: {}
    release: {}
id: 5691a771-39e7-479c-b8e5-1abbe9930c81
images:
    debug: sha256:fe00240aa865648156b4ee0cb6c12d79abc7645a542162f124298ac40e8d6a5d
    release: ''
modificationdate: '2020-05-16T23:06:11.712759'
networks:
    common: []
    debug: []
    release: []
platformid: arm32v7-debian-dotnet_buster
ports:
    common: {}
    debug: {}
    release: {}
privatekey: '-----BEGIN RSA PRIVATE KEY-----

    MIIEogIBAAKCAQEAtUUL5utG2S0EXQjpSg+f/fqFjfVOC15tUBs01B1gPBeUKcYv

    fNjpLX0ghV85cNrnQpITP0WZgdYZ4BuMek4SvWXUhQSH9wmAsfNflWCw7R+kGW6S

    Gcuid97YDvi7MYknIE+F36IsK9ugxWF9iLS75QsDdPMKGxJs9xQXtvL/6AJ0kSjW

    W4NlqneVIEsWRjXynPEXKE3UZ/6UnM6sj++mh1wAJPzYe8u7tpFVsrJuR4fhiF+i

    gWwJClpCSmytfNBHxTkvin7fSclIXjsHMyG/89ObIvOOWd44RNSI/+4I59zGKega

    4rCS4Do4z3pqFaWXryFyLs2z0tVro80U8+B8lQIDAQABAoIBADC15DPiZ4B2q2SA

    v4fqWPj7+CWklJtTfZZ4KSMS3choIaV0H1CyTT6vEC0m4J2mBV0LOebXwh90tDFX

    1dEL59dDZO91vz+wKwgmuTm/6OtfhE5dOx95bChAFtk3F76A96WkGPp2bt4+P56q

    yvwQbSloYz5rDP0nX2ap3JGKDSCAC+8er9MeR0cSNABc0R1ICipLQty9cqPGhE3V

    JU8dF3mYbV0vA7DJnDbw4VEUHQVWtej0DyMH1g83DNnjOf/QYPpRH0m9yEshVXfK

    8elRWnQ2IE4xL2KYmafEyaHc4jomSQnYzIPKdpRZUKpRpwUi2PwEIizCpbf4FZDz

    FbzBFKUCgYEA8HPAJWqGrH3/z2KPHIIpO/94DTkIt4xTlT9jxze3dkThBw6lmCyb

    gZzLOEo67huUAVHEGDLkBZdHTdNofhPuPC4cQxeMzi85meFiwvQxeqrag3qI8DpY

    Z30U6RscnfBfrIutPIDaxNoWO5ODgiM2U9gY/AavVOx7heofas8hH48CgYEAwP2j

    UTFwoW5EWzIk6CG7/IQDb/NsQO8hP+4twPxBr85sZMOJQhXs3YojfiXxLuRsTliB

    wF3AU3iysbNEunMRRucxQE+xoGeQ2bAbytWTOgaTtVCQ6aDS7WWi2e2XK1cwTTwc

    oLXXVxrMXR8XM2/8t3bYHF36fOxI7PbD6On3D5sCgYA2ZVkwnbq9xvtaBSfvARsm

    8ZJNG3v3Wg2GlAKUjOw6Gzb1C8E2fdDoL3phz5kpSJ/g9IhyGQEwqpp85ria3RNm

    FeBa5Tb7Zf+X6j8Xb3rKD2DDobLc9bYOI2PZoEKHEFv0gty79UKIifXBoIt9o02l

    BhwQ18pOYflHwEE/PoB1zQKBgBwtrIfxYRGhCQgLxUnDizAuklXpQ/gjMkakXzfb

    XTfvOvJnfoYQr3oVbmM/5PxEy++QirlstuU5LVY256UVogMpRI6wVC4okQTH6vbt

    wkZpqW2C6vXBzqps+Z86SqVAYMQWL9PjWSLVvdsm6/tNsaeUCa/ypN1Snr9CtI4w

    gytbAoGAao1h0ZaHF6POcUa/5eA45QdnluDzHOO7H9uSpLQAn8pNTtjbU3Whq2M/

    3j7/xJbyZ6+SarKPCCZYsfMHL0Ik7E0YL7qkHls1XkY40l+nTEYeabmVHLNBcyeu

    aqPlUFENhetGRywKLDopdWDVtWlbfN6RCxV2c15WAa5VtKlkNHQ=

    -----END RSA PRIVATE KEY-----

    '
props:
    common:
        appargs: ''
        appname: i2cTest
        arg: ''
        buildcommands: RUN usermod -a -G gpio torizon
        buildfiles: ''
        command: ''
        devpackages: ''
        env: ''
        expose: ''
        extrapackages: ''
        language: dotnet
        preinstallcommands: ''
        runtime: dotnet
        sdkpostinstallcommands: ''
        sdkpreinstallcommands: ''
        targetfiles: ''
    debug:
        arg: 'ARG SSHUSERNAME=#%application.username%#

            '
    release: {}
publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1RQvm60bZLQRdCOlKD5/9+oWN9U4LXm1QGzTUHWA8F5Qpxi982OktfSCFXzlw2udCkhM/RZmB1hngG4x6ThK9ZdSFBIf3CYCx81+VYLDtH6QZbpIZy6J33tgO+LsxiScgT4Xfoiwr26DFYX2ItLvlCwN08wobEmz3FBe28v/oAnSRKNZbg2Wqd5UgSxZGNfKc8RcoTdRn/pSczqyP76aHXAAk/Nh7y7u2kVWysm5Hh+GIX6KBbAkKWkJKbK180EfFOS+Kft9JyUheOwczIb/z05si845Z3jhE1Ij/7gjn3MYp6BrisJLgOjjPemoVpZevIXIuzbPS1WujzRTz4HyV
sdkimages:
    debug: ''
    release: ''
sdksshaddress: null
shutdownscript:
    common: ''
    debug: ''
    release: ''
startupscript:
    common: ''
    debug: ''
    release: ''
username: root
volumes:
    common: {}
    debug:
        /home/torizon/i2cTest: /i2cTest,rw
    release: {}
